In [1]:
import numpy as np

def prepared_data(path):
    file = open(path)
    fr = file.readlines()
    data_list=[]
    y = []
    for data in fr:
        data=data.strip()
        data=data.split(' ')
        data_25 = data[24]
        y.append(data[22])
        del data[-1]
        del data[26]
        del data[25]
        del data[24]
        del data[22]
        del data[2]
        for i in data_25:
            data.append(i)
        data = [0 if data_elem=='?' else float(data_elem) for data_elem in data]
        data_list.append(data)
    data_number = len(y)
    y = np.array([1 if y[j]=='2' or y[j]=='3' else 0 for j in range(data_number)])
    X = np.array(data_list)
    X=np.insert(X,0,1,axis=1)
    return X,y



In [6]:
X,y = prepared_data('./horseColoc-original/horse-colic.data')
X_test,y_test=prepared_data('./horseColoc-original/horse-colic.test')
X_test,y_test

(array([[1., 2., 1., ..., 1., 1., 1.],
        [1., 2., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 2., 0., 5.],
        ...,
        [1., 1., 1., ..., 2., 0., 9.],
        [1., 2., 1., ..., 1., 1., 1.],
        [1., 2., 1., ..., 1., 1., 2.]]),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 1]))

In [7]:
X,y

(array([[1., 2., 1., ..., 3., 0., 0.],
        [1., 1., 1., ..., 2., 0., 8.],
        [1., 2., 1., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 2., 0., 5.],
        [1., 1., 1., ..., 2., 0., 8.],
        [1., 1., 1., ..., 1., 1., 2.]]),
 array([1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 